service: investing-stats-cron

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
custom:
  NASDAQ_API_KEY: grbkFaNNuSzZ2zEbczjW

functions:
  cronHandler:
    handler: source/nasdaq-monthly-pe.run
    events:
      # First day of each month
      - schedule: cron(1 0 1 * ? *)
      # last day of each month
      - schedule: cron(1 0 L * ? *)
